config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "/reviewers", to: "reviewers#index", as: :reviewers
  get "/reviewers/list", to: "reviewers#list", as: :reviewers_list

  get "/mrs", to: "merge_requests#index", as: :merge_requests
  get "/mrs/open_list", to: "merge_requests#open_list", as: :open_merge_requests_list
  get "/mrs/merged_list", to: "merge_requests#merged_list", as: :merged_merge_requests_list
  get "/mrs/merged_chart", to: "merge_requests#merged_chart", as: :merged_merge_requests_chart

  get "/mrs/list", to: redirect("/mrs/open_list")
  get "/mrs/:author", to: "merge_requests#legacy_index"

  get "/api/graph/monthly_merged_mrs",
    to: "api/user_merge_request_charts#monthly_merged_merge_request_stats",
    as: :monthly_merged_merge_request_stats, defaults: {format: :json}

  post "/api/web_push_subscriptions", to: "api/web_push_subscriptions#create", as: :web_push_subscriptions
  post "/api/heartbeat", to: "api/heartbeat#create", as: :heartbeat

  get "/admin/dashboard", to: "admin/dashboard#index", as: :admin_dashboard

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  # Defines the root path route ("/")
  root "merge_requests#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  helper_method :user_cache_validity

  def index
    @users = GitlabUser.all
    @recent_users = GitlabUser.recent.order_by_contacted_at_desc
    @active_users = GitlabUser.active.order_by_contacted_at_desc
  end

  private

  def user_cache_validity(assignee)
    response = MergeRequestsCacheService.new.read(assignee, :open)
    return unless response&.next_scheduled_update_at

    response.next_scheduled_update_at
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
  def boot_timestamp
    GitlabDashboard::Application::BOOTED_AT
  end
end

app/views/admin/dashboard/index.html.erb
<% content_for(:title) { "Admin Dashboard" } %>

<%= tag.div data: {
  controller: "auto-refresh",
  auto_refresh_timeout_value: 30000
} do %>
  <div
    data-controller="bootstrap-tooltip"
    class="container my-3 shadow rounded p-4 bg-body bg-gradient text-body"
  >
    <table class="table table-hover">
      <caption class="caption-top">
        <%= pluralize(number_with_delimiter(@active_users.count), "user dashboard") %>
        currently active, from a total of
        <%= pluralize(number_with_delimiter(@users.count), "visited dashboard") %>
      </caption>

      <thead class="thead-dark">
        <tr>
          <th scope="col">User Handle</th>
          <th scope="col">Created</th>
          <th scope="col">Last Contacted ↓</th>
          <th scope="col">Scheduled Update</th>
        </tr>
      </thead>
      <tbody>
        <% @recent_users.each do |user| %>
          <% one_time_visitor =
            user.contacted_at - user.created_at < CacheConcern::MR_CACHE_VALIDITY %>
          <% fg_class = one_time_visitor ? %w[text-secondary] : nil %>

          <%= tag.tr do %>
            <%= tag.th scope: "row" do %>
              <%= if user.contacted_at&.after?(30.minutes.ago)
                tag.span class: "spinner-grow spinner-grow-sm text-success",
                         aria: {
                           hidden: "true",
                         }
              end %>
              <%= link_to user.username,
              merge_requests_path(author: user.username, referrer: request.fullpath),
              class: fg_class %>
              (<%= link_to "Profile",
              "https://gitlab.com/#{user.username}",
              class: fg_class,
              target: "_blank" %>)
            <% end %>
            <%= tag.td class: fg_class do %>
              <%= render "shared/relative_timestamp", timestamp: user.created_at %>
            <% end %>
            <%= tag.td class: fg_class do %>
              <%= render "shared/relative_timestamp", timestamp: user.contacted_at %>
            <% end %>
            <%= tag.td class: fg_class do %>
              <%= render "shared/relative_timestamp",
              timestamp: user_cache_validity(user.username) %>
            <% end %>
          <% end %>

          <% if user.web_push_subscriptions.any? %>
            <tr>
              <td colspan="4" class="px-5">
                <table class="table table-hover">
                  <caption class="caption-top">Web Push Subscriptions</caption>

                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">Created ↓</th>
                      <th scope="col">Notified</th>
                      <th scope="col">User Agent</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% user.web_push_subscriptions.each do |subscription| %>
                      <tr>
                        <td>
                          <%= render "shared/relative_timestamp", timestamp: subscription.created_at %>
                        </td>
                        <td>
                          <%= render "shared/relative_timestamp", timestamp: subscription.notified_at %>
                        </td>
                        <td>
                          <%= tag.code subscription.user_agent %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div
    data-controller="bootstrap-tooltip"
    class="
      container my-3 d-flex flex-row-reverse column-gap-3 align-items-baseline
    "
  >
    <p class="lead">
      Booted
      <%= render "shared/relative_timestamp", timestamp: boot_timestamp %>
    </p>

    <div class="btn btn-secondary">
      <%= link_to "Jobs", mission_control_jobs_path, class: "text-white" %>
    </div>
  </div>
<% end %>