config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "/reviewers", to: "reviewers#index", as: :reviewers
  get "/reviewers/list", to: "reviewers#list", as: :reviewers_list

  get "/mrs", to: "merge_requests#index", as: :merge_requests
  get "/mrs/open_list", to: "merge_requests#open_list", as: :open_merge_requests_list
  get "/mrs/merged_list", to: "merge_requests#merged_list", as: :merged_merge_requests_list
  get "/mrs/merged_chart", to: "merge_requests#merged_chart", as: :merged_merge_requests_chart

  get "/mrs/list", to: redirect("/mrs/open_list")
  get "/mrs/:author", to: "merge_requests#legacy_index"

  get "/api/graph/monthly_merged_mrs",
    to: "api/user_merge_request_charts#monthly_merged_merge_request_stats",
    as: :monthly_merged_merge_request_stats, defaults: {format: :json}

  post "/api/web_push_subscriptions", to: "api/web_push_subscriptions#create", as: :web_push_subscriptions
  post "/api/heartbeat", to: "api/heartbeat#create", as: :heartbeat

  get "/admin/dashboard", to: "admin/dashboard#index", as: :admin_dashboard

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  # Defines the root path route ("/")
  root "merge_requests#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= turbo_refreshes_with method: :morph, scroll: :preserve if Rails.env.production? %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <%= favicon_link_tag asset_path("favicon.png"), rel: "icon", type: "image/png" %>
    <% %w[57 72 76 114 120 144 152 180].each do |size| %>
      <%= favicon_link_tag asset_path("apple-touch-icon-#{size}x#{size}.png"),
      rel: "apple-touch-icon",
      type: "image/png",
      sizes: "#{size}x#{size}" %>
    <% end %>
    <%= stylesheet_link_tag :application,
    "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_include_tag :application,
    "data-turbo-track": Rails.env.production? ? "reload" : "",
    type: "module" %>
    <script>
      function toggleParagraph(id, link) {
        const para = document.getElementById(id);
        para.classList.toggle('expanded');
        link.textContent = para.classList.contains('expanded') ? 'Show Less' : 'Show More';
      }
    </script>

    <%= debugbar_head if defined?(Debugbar) %>
  </head>
  <!-- Google tag (gtag.js) -->
  <% if ENV["GOOGLE_TAG_MEASUREMENT_ID"].present? %>
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=<%= ENV["GOOGLE_TAG_MEASUREMENT_ID"] %>"
    ></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= ENV["GOOGLE_TAG_MEASUREMENT_ID"] %>');
    </script>
  <% end %>

  <body class="bg-body bg-gradient min-vh-100" data-controller="theme-selector">
    <%= yield %>

    <%= if defined?(Debugbar)
      debugbar_body cable: { url: "wss://#{request.host_with_port}" }
    end %>
  </body>
</html>